spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/databases/forum-test-db
    username: topovv
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  mail:
    host: smtp.mailtrap.io
    port: 587
    username: f7c6241b14b772
    password: 0fbc58b10fc5d9
  data:
    elasticsearch:
      client:
        reactive:
          connection-timeout:


jwt:
  secret: SsaVtRuJttlpTZNUC983FVC3SgH1A0RHzDKtLXAqhJzP5GeHNmR2Yr7ONuZ1sw2G0suCVdaN9QtJ6LpmT531IqFiahebtEgtcDxTMy-CSutFKauR-JGpjxI0YtAJxTYR6xh-DxXEtASt7mPS5_r9vxaswwpceeJy4NgndPbmX9Tm0rVKf_CXqwd4Kffwss8DlUt3jHVEj5Tu5fKp80xrPsnuzZ1C4yG5C11VcjITM-DMTRLsH0dzCJrD_bbj53vZL3RdgocpfCqGfCWF28ULfA0d_KuRXujgEnQ026Rre0amLC8XdgNaw5Z919xeILz5Sn18G7NwuwmuJM0oI4YvWQ

