spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/databases/forum-test-db
    username: topovv
    password: admin
    driver-class-name: org.h2.Driver
<<<<<<< HEAD
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
=======
>>>>>>> 62c9301537cce9a0a160ce1346ae5ab528423925
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.mailtrap.io
    port: 587
    username: f7c6241b14b772
    password: 0fbc58b10fc5d9
