spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/forum
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: db/changelog/db.changelog-master.xml