spring:
  profiles:
    active: prod

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.mailtrap.io
    port: 587
    username: f7c6241b14b772
    password: 0fbc58b10fc5d9

  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
